baseURL = "https://f-lab-USP.github.io"
relativeURLs = "True"
canonifyURLs = "True"
languageCode = "en-us"
title = "f.lab"
themesDir = "themes"
theme = "hugo-hero-theme"
sectionPagesMenu = "content"
enableEmoji = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  google_analytics_id=""
  google_tag_manager_id = ""

 [params.homepage]
  show_call_box = true

 [params.logo]
  mobile = '/images/newlogo.png'
  desktop = '/images/newlogo.png'
  desktop_height = "48px"
  mobile_height = "24px"

  [params.homepage_meta_tags]
    meta_description = "f.lab"
    meta_og_title = "flab"
    meta_og_type = "website"
    meta_og_url = "https://f-lab-USP.github.io"
    meta_og_image = "/static/favicon.png"
    meta_og_description = ""
    meta_twitter_card = "summary"
    meta_twitter_site = "@flab-USP"
    meta_twitter_creator = "@flab-USP"

[[menu.main]]
	name = "Sobre"
	identifier = "about"
	url = "/about/"
    weight = 1

[[menu.main]]
	name = "Pesquisa"
	identifier = "pesquisa"
	url = "/pesquisa/"
    weight = 2

[[menu.main]]
    identifier = "team"
    name = "Grupo"
    url = "/team/"
    weight = 3

[[menu.main]]
    identifier = "current"
    name = "Atuais"
    url = "/team/"
    parent = "team"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
